[workspace]
channels = ["conda-forge"]
name = "ot-algorithm-comparison"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
playground = "python -m uot.test.playground"
color-transfer = "python -m uot.color_transfer.color_transfer"
experiments = "python -m uot.experiments.run_experiments"
split-results = "python -m uot.experiments.split_results"
tests = "python -m uot.experiments.run_tests"
find-distances = "python -m uot.mnist_classification.count_pairwise_distances"
test = "pytest"
bench_gauss = "python -m uot.experiments.synthetic.benchmark_gaussians"
benchmark = "python -m uot.experiments.synthetic.benchmark"