[workspace]
channels = ["conda-forge"]
name = "ot-algorithm-comparison"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
color-transfer = "python -m uot.color_transfer.color_transfer"
tp-experiment = "python -m uot.experiments.time_precision_experiments"

[dependencies]
