[workspace]
channels = ["conda-forge"]
name = "ot-algorithm-comparison"
platforms = ["linux-64", "win-64", "osx-64"]
version = "0.1.0"

[tool.pixi.source]
root = "uot"

[tasks]
playground = "python -m uot.test.playground"
color-transfer = "python -m uot.experiments.real_data.color_transfer.color_transfer"
color-transfer-visualization = "python -m uot.experiments.real_data.color_transfer.visualization"
mnist_distances = "python -m uot.experiments.real_data.mnist_classification.count_pairwise_distances"
mnist_classification = "python -m uot.experiments.real_data.mnist_classification.mnist_classification"
tests = "python -m uot.experiments.run_tests"
test = "pytest"
benchmark = "python -m uot.experiments.synthetic.benchmark"
serialize = "python -m uot.problems.problem_serializer"
inspect-store = "python -m uot.problems.inspect_store"
lint = "ruff check ."

[dependencies]
black = ">=25.1.0,<26"
pyyaml = ">=6.0.2,<7"
plotly = ">=6.2.0,<7"
dash = ">=3.0.4,<4"
pillow = ">=11.3.0,<12"
numpy = ">=2.3.1,<3"
pandas = ">=2.3.0,<3"
