generators:
  2D-students-t-16p:
    generator: uot.problems.generators.StudentTGenerator
    dim: 2
    nu: 4
    n_points: 16
    num_datasets: 2
    cost_fn: uot.utils.costs.cost_euclid_squared
    borders: (-10, 10)
    seed: 42

  2D-gen-hyperb-mixture-1c-16p:
    generator: uot.problems.generators.GeneralizedHyperbolicMixtureGenerator
    dim: 2
    n_points: 16
    num_components: 1
    num_datasets: 2
    borders: (-10, 10)
    lambda_bounds: [-1.0, 2]
    alpha_bounds: [0.5, 5.0]
    beta_coef: 0.9
    delta_bounds: [0.1, 2.0]
    cost_fn: uot.utils.costs.cost_euclid_squared
    seed: 42

  2D-indep-cauchy-16p:
    generator: uot.problems.generators.IndependentCauchyGenerator
    dim: 2
    n_points: 16
    num_datasets: 2
    borders: [-10, 10]
    cost_fn: uot.utils.costs.cost_euclid_squared
    seed: 42

  2D-indep-exp-16p:
    generator: uot.problems.generators.IndependentExponentialGenerator
    dim: 2
    n_points: 16
    num_datasets: 2
    borders: [-10, 10]
    cost_fn: uot.utils.costs.cost_euclid_squared
    seed: 42
