param-grids:
  sinkhorn_params:
    - reg: 1
      maxiter: 1000000
    - reg: 0.001
      maxiter: 1000000

  gradient_ascent_params:
    - reg: 1
      maxiter: 10000000
    - reg: 0.001
      maxiter: 10000000


solvers:
  sinkhorn:
    solver: uot.solvers.sinkhorn.SinkhornTwoMarginalSolver
    jit: true
    param-grid: sinkhorn_params
  gradient-ascent:
    solver: uot.solvers.gradient_ascent.GradientAscentTwoMarginalSolver
    jit: true
    param-grid: gradient_ascent_params

problems:
  dir: /home/izhytkevych/datasets/synthetic_gauss_exp_cauchy
  names:
    - 1D-gaussians-1c-64p
    - 1D-gaussians-1c-128p
    - 1D-gaussians-1c-256p
    - 1D-gaussians-2c-256p
    - 1D-gaussians-1c-512p
    - 1D-gaussians-2c-512p
    - 1D-gaussians-3c-512p
    - 1D-gaussians-1c-1024p
    - 1D-gaussians-2c-1024p
    - 1D-gaussians-3c-1024p
    - 1D-gaussians-1c-2048p
    - 1D-gaussians-2c-2048p
    - 1D-gaussians-3c-2048p
    - 1D-gaussians-1c-4096p
    - 1D-gaussians-2c-4096p
    - 1D-gaussians-3c-4096p
    - 1D-gaussians-4c-4096p
    - 1D-gaussians-1c-8192p
    - 1D-gaussians-2c-8192p
    - 1D-gaussians-3c-8192p
    - 1D-gaussians-4c-8192p
    - 1D-gaussians-5c-8192p
    - 1D-gaussians-10c-8192p
    - 1D-gaussians-1c-16384p
    - 1D-gaussians-2c-16384p
    - 1D-gaussians-3c-16384p
    - 1D-gaussians-4c-16384p
    - 1D-gaussians-5c-16384p
    - 1D-gaussians-10c-16384p
    - 1D-gaussians-1c-32768p
    - 1D-gaussians-2c-32768p
    - 1D-gaussians-3c-32768p
    - 1D-gaussians-4c-32768p
    - 1D-gaussians-5c-32768p
    - 1D-gaussians-10c-32768p
    - 2D-gaussians-1c-32p
    - 2D-gaussians-1c-64p
    - 2D-gaussians-2c-64p
    - 2D-gaussians-3c-64p
    - 2D-gaussians-1c-96p
    - 2D-gaussians-2c-96p
    - 2D-gaussians-3c-96p
    - 2D-gaussians-1c-128p
    - 2D-gaussians-1c-160p
    - 2D-gaussians-1c-192p

    - 1D-cauchy-64p
    - 1D-cauchy-128
    - 1D-cauchy-256
    - 1D-cauchy-512
    - 1D-cauchy-1024
    - 1D-cauchy-2048
    - 1D-cauchy-4096
    - 1D-cauchy-8192
    - 1D-cauchy-16384
    - 1D-cauchy-32768

    - 1D-exponential-64p
    - 1D-exponential-128p
    - 1D-exponential-256
    - 1D-exponential-512
    - 1D-exponential-1024
    - 1D-exponential-2048
    - 1D-exponential-4096
    - 1D-exponential-8192
    - 1D-exponential-16384
    - 1D-exponential-32768  

experiment: 
  name: Time and GPU usage test
  function: uot.experiments.measurement.measure_with_gpu_tracker
