param-grids:
  epsilons:
    - reg: 1
    - reg: 0.001

solvers:
  sinkhorn:
    solver: uot.solvers.sinkhorn.SinkhornTwoMarginalSolver
    jit: true
    param-grid: epsilons

problems:
  dir: datasets/synthetic
  names:
    - 1D-gaussians-64