param-grids:
  regularizations:
    - reg: 1
    - reg: 0.001

solvers:
  gradient-ascent:
    solver: uot.solvers.gradient_ascent.GradientAscentTwoMarginalSolver
    jit: true
    param-grid: regularizations

problems:
  dir: datasets/synthetic
  names:
    - 1D-gaussians-64
  
experiment: 
  name: Measure on Gaussians
  function: uot.experiments.measurement.measure_time
