generators:
  _cauchy_defaults: &cauchy_defaults
    generator: uot.problems.generators.CauchyGenerator
    dim: 1
    num_datasets: 5
    cost_fn: uot.utils.costs.cost_euclid_squared
    use_jax: false
    borders: (-10, 10)
    seed: 42

  _exponential_defaults: &exponential_defaults
    generator: uot.problems.generators.ExponentialGenerator
    dim: 1
    num_datasets: 5
    cost_fn: uot.utils.costs.cost_euclid_squared
    use_jax: false
    seed: 42
    borders: (-1, 20)

  _gauss_default: &gauss_default
    generator: uot.problems.generators.GaussianMixtureGenerator
    num_components: 1
    num_datasets: 5
    borders: (-6, 6)
    cost_fn: uot.utils.costs.cost_euclid_squared
    use_jax: false
    seed: 42

  1D-cauchy-32p:
    <<: *cauchy_defaults
    n_points: 32

  1D-cauchy-64p:
    <<: *cauchy_defaults
    n_points: 64

  1D-exponential-32p:
    <<: *exponential_defaults
    n_points: 32

  1D-exponential-64p:
    <<: *exponential_defaults
    n_points: 64

  1D-gaussians-1c-32p:
    <<: *gauss_default
    dim: 1
    n_points: 32

  1D-gaussians-1c-64p:
    <<: *gauss_default
    dim: 1
    n_points: 64

  1D-gaussians-2c-32p:
    <<: *gauss_default
    dim: 1
    n_points: 32
    num_components: 2

  1D-gaussians-4c-128p:
    <<: *gauss_default
    dim: 1
    n_points: 128
    num_components: 4
    borders: (-10, 10)

  1D-cauchy-vs-gmm-64p:
    generator: uot.problems.generators.PairedGenerator
    __subgenerator_defaults: &cauchy_vs_gmm_64p_subgenerator_defaults
      dim: 1
      n_points: 64
      borders: [-3, 3]
      cost_fn: uot.utils.costs.cost_euclid_squared
      use_jax: false
    num_datasets: 5
    gen_a_cfg:
      class: uot.problems.generators.CauchyGenerator
      params:
        <<: *cauchy_vs_gmm_64p_subgenerator_defaults
        seed: 42
    gen_b_cfg:
      class: uot.problems.generators.GaussianMixtureGenerator
      params:
        <<: *cauchy_vs_gmm_64p_subgenerator_defaults
        seed: 24
        num_components: 2

  1D-exp-vs-gmm-64p:
    generator: uot.problems.generators.PairedGenerator
    __subgenerator_defaults: &exp_vs_gmm_64p_subgenerator_defaults
      dim: 1
      n_points: 64
      borders: [-3, 3]
      cost_fn: uot.utils.costs.cost_euclid_squared
      use_jax: false
    num_datasets: 5
    gen_a_cfg:
      class: uot.problems.generators.ExponentialGenerator
      params:
        <<: *exp_vs_gmm_64p_subgenerator_defaults
        seed: 42
    gen_b_cfg:
      class: uot.problems.generators.GaussianMixtureGenerator
      params:
        <<: *exp_vs_gmm_64p_subgenerator_defaults
        seed: 24
        num_components: 2

  1D-exp-vs-cauchy-64p:
    generator: uot.problems.generators.PairedGenerator
    __subgenerator_defaults: &exp_vs_cauchy_64p_subgenerator_defaults
      dim: 1
      n_points: 64
      borders: [-3, 3]
      cost_fn: uot.utils.costs.cost_euclid_squared
      use_jax: false
    num_datasets: 5
    gen_a_cfg:
      class: uot.problems.generators.ExponentialGenerator
      params:
        <<: *exp_vs_cauchy_64p_subgenerator_defaults
        seed: 42
    gen_b_cfg:
      class: uot.problems.generators.CauchyGenerator
      params:
        <<: *exp_vs_cauchy_64p_subgenerator_defaults
        seed: 24
