generators:
  _cauchy_defaults: &cauchy_defaults
    generator: uot.problems.generators.CauchyGenerator
    dim: 1
    num_datasets: 30
    cost_fn: uot.utils.costs.cost_euclid_squared
    use_jax: true
    seed: 42

  1D-cauchy-32p:
    <<: *cauchy_defaults
    n_points: 32
    borders: (0, 1)

  1D-cauchy-wide-32p:
    <<: *cauchy_defaults
    n_points: 32
    borders: (-1, 1)

  1D-cauchy-64p:
    <<: *cauchy_defaults
    n_points: 64
    borders: (0, 1)

  1D-cauchy-wide-64p:
    <<: *cauchy_defaults
    n_points: 64
    borders: (-1, 1)
