generators:
  _exponential_defaults: &exponential_defaults
    generator: uot.problems.generators.ExponentialGenerator
    dim: 1
    num_datasets: 8
    cost_fn: uot.utils.costs.cost_euclid_squared
    use_jax: true
    seed: 42
    borders: (-10, 10)

  1D-exponential-32p:
    <<: *exponential_defaults
    n_points: 32

  1D-exponential-64p:
    <<: *exponential_defaults
    n_points: 64
