generators:
  _exponential_defaults: &exp_defaults
    generator: uot.problems.generators.ExponentialGenerator
    dim: 1
    n_points: 64
    num_datasets: 30
    borders: (-6, 6)
    cost_fn: uot.utils.costs.cost_euclid_squared
    use_jax: true
    seed: 42

  # ─── 1D distributions ────────────────────────────────────────────────────────
  1D-exponential-64p:
    <<: *exp_defaults
    n_points: 64

  1D-exponential-128p:
    <<: *exp_defaults
    n_points: 128

  1D-exponential-256:
    <<: *exp_defaults
    n_points: 256

  1D-exponential-512:
    <<: *exp_defaults
    n_points: 512

  1D-exponential-1024:
    <<: *exp_defaults
    n_points: 1024

  1D-exponential-2048:
    <<: *exp_defaults
    n_points: 2048

  1D-exponential-4096:
    <<: *exp_defaults
    n_points: 4096
    
  1D-exponential-8192:
    <<: *exp_defaults
    n_points: 8192

  1D-exponential-16384:
    <<: *exp_defaults
    n_points: 16384

  1D-exponential-32768:
    <<: *exp_defaults
    n_points: 32768
