generators:
  _gaussian_defaults: &gauss_defaults
    generator: uot.problems.generators.GaussianMixtureGenerator
    num_components: 1
    num_datasets: 30
    borders: (-1, 1)
    cost_fn: uot.utils.costs.cost_euclid_squared
    use_jax: true
    seed: 42

  # ─── 1D mixtures ────────────────────────────────────────────────────────
  1D-gaussians-1c-64p:
    <<: *gauss_defaults
    dim: 1
    n_points: 64

  1D-gaussians-1c-128p:
    <<: *gauss_defaults
    dim: 1
    n_points: 128

  1D-gaussians-1c-256p:
    <<: *gauss_defaults
    dim: 1
    n_points: 256

  1D-gaussians-2c-256p:
    <<: *gauss_defaults
    dim: 1
    n_points: 256
    num_components: 2

  1D-gaussians-1c-512p:
    <<: *gauss_defaults
    dim: 1
    n_points: 512

  1D-gaussians-2c-512p:
    <<: *gauss_defaults
    dim: 1
    n_points: 512
    num_components: 2

  1D-gaussians-3c-512p:
    <<: *gauss_defaults
    dim: 1
    n_points: 512
    num_components: 3

  1D-gaussians-1c-1024p:
    <<: *gauss_defaults
    dim: 1
    n_points: 1024

  1D-gaussians-2c-1024p:
    <<: *gauss_defaults
    dim: 1
    n_points: 1024
    num_components: 2

  1D-gaussians-3c-1024p:
    <<: *gauss_defaults
    dim: 1
    n_points: 1024
    num_components: 3

  1D-gaussians-1c-2048p:
    <<: *gauss_defaults
    dim: 1
    n_points: 2048

  1D-gaussians-2c-2048p:
    <<: *gauss_defaults
    dim: 1
    n_points: 2048
    num_components: 2

  1D-gaussians-3c-2048p:
    <<: *gauss_defaults
    dim: 1
    n_points: 2048
    num_components: 3

  1D-gaussians-1c-4096p:
    <<: *gauss_defaults
    dim: 1
    n_points: 4096

  1D-gaussians-2c-4096p:
    <<: *gauss_defaults
    dim: 1
    n_points: 4096
    num_components: 2

  1D-gaussians-3c-4096p:
    <<: *gauss_defaults
    dim: 1
    n_points: 4096
    num_components: 3

  1D-gaussians-4c-4096p:
    <<: *gauss_defaults
    dim: 1
    n_points: 4096
    num_components: 4

  1D-gaussians-1c-8192p:
    <<: *gauss_defaults
    dim: 1
    n_points: 8192

  1D-gaussians-2c-8192p:
    <<: *gauss_defaults
    dim: 1
    n_points: 8192
    num_components: 2

  1D-gaussians-3c-8192p:
    <<: *gauss_defaults
    dim: 1
    n_points: 8192
    num_components: 3

  1D-gaussians-4c-8192p:
    <<: *gauss_defaults
    dim: 1
    n_points: 8192
    num_components: 4

  1D-gaussians-5c-8192p:
    <<: *gauss_defaults
    dim: 1
    n_points: 8192
    num_components: 5

  1D-gaussians-10c-8192p:
    <<: *gauss_defaults
    dim: 1
    n_points: 8192
    num_components: 10

  1D-gaussians-1c-16384p:
    <<: *gauss_defaults
    dim: 1
    n_points: 16384

  1D-gaussians-2c-16384p:
    <<: *gauss_defaults
    dim: 1
    n_points: 16384
    num_components: 2

  1D-gaussians-3c-16384p:
    <<: *gauss_defaults
    dim: 1
    n_points: 16384
    num_components: 3

  1D-gaussians-4c-16384p:
    <<: *gauss_defaults
    dim: 1
    n_points: 16384
    num_components: 4

  1D-gaussians-5c-16384p:
    <<: *gauss_defaults
    dim: 1
    n_points: 16384
    num_components: 5

  1D-gaussians-10c-16384p:
    <<: *gauss_defaults
    dim: 1
    n_points: 16384
    num_components: 10

  1D-gaussians-1c-32768p:
    <<: *gauss_defaults
    dim: 1
    n_points: 32768

  1D-gaussians-2c-32768p:
    <<: *gauss_defaults
    dim: 1
    n_points: 32768
    num_components: 2

  1D-gaussians-3c-32768p:
    <<: *gauss_defaults
    dim: 1
    n_points: 32768
    num_components: 3

  1D-gaussians-4c-32768p:
    <<: *gauss_defaults
    dim: 1
    n_points: 32768
    num_components: 4

  1D-gaussians-5c-32768p:
    <<: *gauss_defaults
    dim: 1
    n_points: 32768
    num_components: 5

  1D-gaussians-10c-32768p:
    <<: *gauss_defaults
    dim: 1
    n_points: 32768
    num_components: 10


  # ─── 2D mixtures ────────────────────────────────────────────────────────
  2D-gaussians-1c-32p:
    <<: *gauss_defaults
    dim: 2
    n_points: 32
    num_components: 1

  2D-gaussians-1c-64p:
    <<: *gauss_defaults
    dim: 2
    n_points: 64
    num_components: 1

  2D-gaussians-2c-64p:
    <<: *gauss_defaults
    dim: 2
    n_points: 64
    num_components: 2

  2D-gaussians-3c-64p:
    <<: *gauss_defaults
    dim: 2
    n_points: 64
    num_components: 3

  2D-gaussians-1c-96p:
    <<: *gauss_defaults
    dim: 2
    n_points: 96
    num_components: 1

  2D-gaussians-2c-96p:
    <<: *gauss_defaults
    dim: 2
    n_points: 96
    num_components: 2

  2D-gaussians-3c-96p:
    <<: *gauss_defaults
    dim: 2
    n_points: 96
    num_components: 3

  2D-gaussians-1c-128p:
    <<: *gauss_defaults
    dim: 2
    n_points: 128
    num_components: 1

  2D-gaussians-1c-160p:
    <<: *gauss_defaults
    dim: 2
    n_points: 160
    num_components: 1

  2D-gaussians-1c-192p:
    <<: *gauss_defaults
    dim: 2
    n_points: 192
    num_components: 1

  # in theory, after 316 points H100 will blow up (max 80GiB)
