generators:
  1D-gaussians-64:
    generator: uot.problems.generators.GaussianMixtureGenerator
    dim: 1
    num_components: 1
    n_points: 64
    num_datasets: 30
    borders: (-10, 10)
    cost_fn: uot.utils.costs.cost_euclid_squared
    use_jax: true
    seed: 42

  1D-gaussians-128:
    generator: uot.problems.generators.GaussianMixtureGenerator
    dim: 1
    num_components: 1
    n_points: 128
    num_datasets: 30
    borders: (-10, 10)
    cost_fn: uot.utils.costs.cost_euclid_squared
    use_jax: true
    seed: 42

  1D-gaussians-512:
    generator: uot.problems.generators.GaussianMixtureGenerator
    dim: 1
    num_components: 1
    n_points: 512
    num_datasets: 30
    borders: (-10, 10)
    cost_fn: uot.utils.costs.cost_euclid_squared
    use_jax: true
    seed: 42

  1D-gaussians-1024:
    generator: uot.problems.generators.GaussianMixtureGenerator
    dim: 1
    num_components: 1
    n_points: 1024
    num_datasets: 30
    borders: (-10, 10)
    cost_fn: uot.utils.costs.cost_euclid_squared
    use_jax: true
    seed: 42
