generators:
  _gauss_default: &gauss_default
    generator: uot.problems.generators.GaussianMixtureGenerator
    num_components: 1
    num_datasets: 6
    borders: (-6, 6)
    cost_fn: uot.utils.costs.cost_euclid_squared
    use_jax: False
    seed: 42
    

  1D-gaussians-1c-32p:
    <<: *gauss_default
    dim: 1
    n_points: 32

  1D-gaussians-narrow-1c-32p:
    <<: *gauss_default
    dim: 1
    n_points: 32
    borders: (-1, 1)

  1D-gaussians-2c-32p:
    <<: *gauss_default
    dim: 1
    n_points: 32
    num_components: 2

  1D-gaussians-4c-128p:
    <<: *gauss_default
    dim: 1
    n_points: 128
    num_components: 4
    borders: (-10, 10)
