generators:
  1D-mixgaussians-64:
    generator: uot.problems.generators.GaussianMixtureGenerator
    dim: 1
    num_components: 2
    n_points: 64
    num_datasets: 30
    borders: (-1, 1)
    cost_fn: uot.utils.costs.cost_euclid_squared
    use_jax: true
    seed: 42

  1D-mixgaussians-128:
    generator: uot.problems.generators.GaussianMixtureGenerator
    dim: 1
    num_components: 2
    n_points: 128
    num_datasets: 30
    borders: (-1, 1)
    cost_fn: uot.utils.costs.cost_euclid_squared
    use_jax: true
    seed: 42

  1D-mixgaussians-256:
    generator: uot.problems.generators.GaussianMixtureGenerator
    dim: 1
    num_components: 3
    n_points: 256
    num_datasets: 30
    borders: (-1, 1)
    cost_fn: uot.utils.costs.cost_euclid_squared
    use_jax: true
    seed: 42

  1D-mixgaussians-512:
    generator: uot.problems.generators.GaussianMixtureGenerator
    dim: 1
    num_components: 3
    n_points: 512
    num_datasets: 30
    borders: (-1, 1)
    cost_fn: uot.utils.costs.cost_euclid_squared
    use_jax: true
    seed: 42

  1D-mixgaussians-1024:
    generator: uot.problems.generators.GaussianMixtureGenerator
    dim: 1
    num_components: 4
    n_points: 1024
    num_datasets: 30
    borders: (-1, 1)
    cost_fn: uot.utils.costs.cost_euclid_squared
    use_jax: true
    seed: 42

  1D-mixgaussians-2048:
    generator: uot.problems.generators.GaussianMixtureGenerator
    dim: 1
    num_components: 4
    n_points: 2048
    num_datasets: 30
    borders: (-1, 1)
    cost_fn: uot.utils.costs.cost_euclid_squared
    use_jax: true
    seed: 42

  1D-mixgaussians-4096:
    generator: uot.problems.generators.GaussianMixtureGenerator
    dim: 1
    num_components: 4
    n_points: 4096
    num_datasets: 30
    borders: (-1, 1)
    cost_fn: uot.utils.costs.cost_euclid_squared
    use_jax: true
    seed: 42

  1D-mixgaussians-8192:
    generator: uot.problems.generators.GaussianMixtureGenerator
    dim: 1
    num_components: 4
    n_points: 8192
    num_datasets: 30
    borders: (-1, 1)
    cost_fn: uot.utils.costs.cost_euclid_squared
    use_jax: true
    seed: 42

  1D-mixgaussians-16384:
    generator: uot.problems.generators.GaussianMixtureGenerator
    dim: 1
    num_components: 5
    n_points: 16384
    num_datasets: 30
    borders: (-1, 1)
    cost_fn: uot.utils.costs.cost_euclid_squared
    use_jax: true
    seed: 42

  2D-mixgaussians-64:
    generator: uot.problems.generators.GaussianMixtureGenerator
    dim: 2
    num_components: 2
    n_points: 64
    num_datasets: 30
    borders: (-1, 1)
    cost_fn: uot.utils.costs.cost_euclid_squared
    use_jax: true
    seed: 42

  2D-mixgaussians-128:
    generator: uot.problems.generators.GaussianMixtureGenerator
    dim: 2
    num_components: 2
    n_points: 128
    num_datasets: 30
    borders: (-1, 1)
    cost_fn: uot.utils.costs.cost_euclid_squared
    use_jax: true
    seed: 42

  2D-mixgaussians-256:
    generator: uot.problems.generators.GaussianMixtureGenerator
    dim: 2
    num_components: 3
    n_points: 256
    num_datasets: 30
    borders: (-1, 1)
    cost_fn: uot.utils.costs.cost_euclid_squared
    use_jax: true
    seed: 42

  2D-mixgaussians-512:
    generator: uot.problems.generators.GaussianMixtureGenerator
    dim: 2
    num_components: 3
    n_points: 512
    num_datasets: 30
    borders: (-1, 1)
    cost_fn: uot.utils.costs.cost_euclid_squared
    use_jax: true
    seed: 42

  2D-mixgaussians-1024:
    generator: uot.problems.generators.GaussianMixtureGenerator
    dim: 2
    num_components: 4
    n_points: 1024
    num_datasets: 30
    borders: (-1, 1)
    cost_fn: uot.utils.costs.cost_euclid_squared
    use_jax: true
    seed: 42
