params:
  epsilons:
    - epsilon: 1
    - epsilon: 0.1
    - epsilon: 0.001

solvers:
  lp:
    function: uot.algorithms.lp.pot_lp
    jit: false
    params: 
  sinkhorn:
    function: uot.algorithms.sinkhorn.jax_sinkhorn
    jit: true
    params: epsilons
  gradient-ascent:
    function: uot.algorithms.gradient_ascent.gradient_ascent
    jit: true
    params: epsilons
  lbfgs:
    function: uot.algorithms.lbfgs.lbfgs_ot
    jit: true
    params: epsilons

problemsets:
  - distribution-gaussian-32